### ISSUE TITLE
panic caused by empty device model info 

### ISSUE THREAD

**Issue by will-mei** [plutobell/pi-dashboard-go#1]
raspberrypi zero-w

error: 
```
[PANIC RECOVER] runtime error: index out of range [1] with length 1 goroutine 9 [running]:
github.com/labstack/echo/v4/middleware.RecoverWithConfig.func1.1.1(0x45a84c, 0x1000, 0x0, 0x4c5914, 0x24819e0)
        /home/pi/go/pkg/mod/github.com/labstack/echo/v4@v4.1.17/middleware/recover.go:77 +0xa8
panic(0x40d8b0, 0x241d630)
        /usr/local/go/src/runtime/panic.go:965 +0x174
main.Device(0x0)
        /home/pi/pi-dashboard-go/device.go:113 +0x3a34
```

fix : 

`device.go` :69

```
-               "model":            "cat /proc/cpuinfo | grep Model",
+               "model":            "cat /proc/cpuinfo | grep -i Model |sort -u |head -1",
```

**Comment by plutobell** [comment]
Thanks for Issue, this bug has been fixed in version 1.0.10.
